### ISSUE TITLE
Simple way to edit positive/negative word lists?

### ISSUE THREAD

**Issue by PoLabs** [Displayr/flipTextAnalysis#1]
Hello, is there an easy way to add custom positive/negative sentiment words to the packages lists?

I see the 'ftaNegativeWords.rda' and 'ftaPositiveWords.rda' files but I'm trying to avoid to avoid attempting to edit them and rebuild the package. Atleast I think this would be difficult.

**Comment by jakehoare** [comment]
Hihi  I added `supplementary.pos.words` and `supplementary.neg.words` parameters that allow you to add custom words to the built-in lists. Should get you what you want.

**Comment by PoLabs** [comment]
Nice! I forked the package and entered the keywords directly into the sentiment.R file. So...I think it's working correctly, hard to tell.
